name: Build DotNet Api
run-name: "Build ${{ inputs.BUILD_VERSION }} | Branch: ${{ github.ref_name }}"

on:
  workflow_dispatch:
    inputs:
      DRY_RUN:
        description: 'Turn dry-run mode on or off.'
        required: false
        type: choice
        default: 'true'
        options:
          - 'true'
          - 'false'
      
      VARIABLES_TO_SYNC:
        description: 'Accepted formats: JSON array (e.g. ["VAR_A", "VAR_B"]) or comma-separated, no space, string (e.g. VAR_A,VAR_B).'
        required: false
        type: string
        default: '[]'
      
      AMBIENTES:
        description: "Ambientes (Não PRD)"
        required: false
        default: '["des"]'
        type: choice
        options:
          - '["des"]'
          - '["qa"]'
          - '["tqs"]'
          - '["prd"]'
          - '["des","qa"]'
          - '["des","tqs"]'
          - '["des","prd"]'
          - '["des","qa","tqs"]'
          - '["des","qa","tqs","prd"]'
      BUILD_VERSION:
        description: 'Informe a versão da API:'
        required: true
        type: string
        default: '0.0.5'
      TEST_RUN:
        description: "Run Test Unit"
        required: true
        type: boolean
        default: false
      SEC_RUN:
        description: "Run Adv Sec"
        required: true
        type: boolean
        default: false
      QA_RUN:
        description: "Run QA SonarQube"
        required: true
        type: boolean
        default: false
      INTEGRATION_RUN:
        description: "Run Integration Test"
        required: true
        type: boolean
        default: false

permissions:
  packages: write
  contents: write
  actions: read
  security-events: write
  id-token: write

jobs:
  workflow:
    uses: Illusion-Factory-Labs/github-repo-templates/.github/workflows/dotnet-api-workflow.yaml@main
    secrets: inherit
    with:
      BUILD_VERSION: '${{ inputs.BUILD_VERSION }}'
      TEST_RUN: '${{ inputs.TEST_RUN }}'
      SEC_RUN: '${{ inputs.SEC_RUN }}'
      QA_RUN: '${{ inputs.QA_RUN }}'
      INTEGRATION_RUN: '${{ inputs.INTEGRATION_RUN }}'
      AMBIENTES: '${{ inputs.AMBIENTES }}'
      DOTNET_VERSION: '8.x'
      dry_run: '${{ inputs.DRY_RUN }}'
      variables_to_sync: '${{ inputs.VARIABLES_TO_SYNC }}'
