name: Playground Workflow

on:
  workflow_dispatch:
    inputs:
      DRY_RUN_SYNC:
        description: 'Turn dry-run mode on or off for variable synchronization.'
        required: false
        type: choice
        default: 'false'
        options:
          - 'true'
          - 'false'
      DRY_RUN_ENV:
        description: 'Turn dry-run mode on or off for environment removal.'
        required: false
        type: choice
        default: 'false'
        options:
          - 'true'
          - 'false'
      VARS_TO_SYNC:
        description: >-
          'Optional comma of source variable names to sync. Accepted formats: JSON array (e.g. ["VAR_A", "VAR_B"]) or 
          comma-separated, no space, string (e.g. VAR_A,VAR_B). Defaults to empty JSON array, which means sync all source variables.'
        required: false
        type: string
        default: '[]'
      

permissions:
  contents: read

env:
  GLOBAL_REPO_VAR: github-repo-variables
  GH_PAT: ${{ secrets.GH_PAT }}
  WF_APP_ID: ${{ secrets.WF_APP_ID }}
  WF_APP_PRIVATE_KEY: ${{ secrets.WF_APP_PRIVATE_KEY }}
  GITHUB_REPOSITORY_OWNER: ${{ github.repository_owner }}

defaults:
  run:
    shell: bash

jobs:
  test-variables:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        AMBIENTE: [des, prd, qa, tqs]
    environment: ${{ matrix.AMBIENTE == 'prd' && 'prd-vars' || (matrix.AMBIENTE == 'tqs' &&  'tqs-vars' || matrix.AMBIENTE) }}
    steps:
      - name: Gerar token para autenticação com a API do GitHub
        uses: Illusion-Factory-Labs/github-repo-templates/actions/auth/generate-gh-token@main
      
      - name: "Sincronizar variáveis de ambiente"
        id: sync-vars  
        if: ${{ matrix.AMBIENTE == 'prd' || matrix.AMBIENTE == 'tqs' }}
        uses: Illusion-Factory-Labs/github-repo-templates/actions/components/sync-existing-env-vars@main
        with:
          DRY_RUN_SYNC: ${{ inputs.DRY_RUN_SYNC }}
          VARS_TO_SYNC: ${{ inputs.VARS_TO_SYNC }}
      
  remove-env:
    needs: test-variables
    if: ${{ always() }}
    runs-on: ubuntu-latest
    steps:
      - name: Gerar token para autenticação com a API do GitHub
        uses: Illusion-Factory-Labs/github-repo-templates/actions/auth/generate-gh-token@main
        
      - name: "Remover ambientes variáveis temporários"
        id: remove-envs
        uses: Illusion-Factory-Labs/github-repo-templates/actions/components/remove-github-env@main
        with:
          DRY_RUN_ENV: ${{ inputs.DRY_RUN_ENV }}