name: Playground Workflow

on:
  workflow_dispatch:
    inputs:
      AMBIENTES:
        required: false
        type: string
        default: '["des"]'

permissions:
  contents: read

env:
  GLOBAL_REPO_VAR: github-repo-variables
  GH_PAT: ${{ secrets.GH_PAT }}
  WF_APP_ID: ${{ secrets.WF_APP_ID }}
  WF_APP_PRIVATE_KEY: ${{ secrets.WF_APP_PRIVATE_KEY }}
  GITHUB_REPOSITORY_OWNER: ${{ github.repository_owner }}

defaults:
  run:
    shell: bash

jobs:
  test-variables:
    runs-on: ubuntu-latest
    name: test-variables-${{ matrix.AMBIENTE }}
    outputs:
      json: ${{ steps.matrix-output.outputs.json }}
    strategy:
      matrix:
        AMBIENTE: ${{ inputs.AMBIENTES }}
    environment: ${{ matrix.AMBIENTE == 'prd' && 'prd-temp' || (matrix.AMBIENTE == 'tqs' &&  'tqs-temp' || matrix.AMBIENTE) }}
    steps:
      - name: "Api Dotnet Variables"
        uses: Illusion-Factory-Labs/github-repo-templates/actions/context/dotnet-api@main
      - name: "Token Create"
        uses: Illusion-Factory-Labs/github-repo-templates/actions/auth/githubapp@main
      - name: "Sincronizar ambiente temporário para importação de variáveis (evitar aprovação manual)"
        id: sync-temp-env-vars
        if: ${{ matrix.AMBIENTE == 'prd' || matrix.AMBIENTE == 'tqs' }}
        uses: Illusion-Factory-Labs/github-repo-templates/actions/components/sync-github-env-vars@main
      - name: "File Variable Groups '${{ matrix.AMBIENTE }}'"
        id: file-variable-group
        uses: Illusion-Factory-Labs/github-repo-templates/actions/components/file-variable-group@main
      - name: "Load Variable Groups '${{ matrix.AMBIENTE }}'"
        uses: Illusion-Factory-Labs/github-repo-templates/actions/components/load-variable-group@main
        with:
          VARS_FILE: ${{ steps.file-variable-group.outputs.VARS_FILE }}
          VARS_CONTEXT: ${{ toJson(vars) }}
          VARS_TEMP_ENV: ${{ steps.sync-temp-env-vars.outputs.changed_variables_json }}
      - name: Exportar ambientes temporários para os próximos jobs
        if: ${{ matrix.AMBIENTE == 'prd' || matrix.AMBIENTE == 'tqs' }}
        run: beacon-biosignals/matrix-output@v1
        id: matrix-output
        with:
          yaml: |
            ambiente: "${{ matrix.AMBIENTE }}-temp"
  
  remove-temp-env:
    runs-on: ubuntu-latest
    needs: test-variables
    if: ${{ matrix.AMBIENTE.ambiente == 'prd-temp' || matrix.AMBIENTE.ambiente == 'tqs-temp' }}
    strategy:
      matrix:
        AMBIENTE: ${{ fromJSON(needs.test-variables.outputs.json).ambiente }}
    steps:
      - name: "Token Create"
        uses: Illusion-Factory-Labs/github-repo-templates/actions/auth/githubapp@main
        
      - name: "Remover ambiente temporário de importação de variáveis"
        uses: Illusion-Factory-Labs/github-repo-templates/actions/components/remove-github-env@main
      
      # - name: "Create Configmap"
      #   uses: Illusion-Factory-Labs/github-repo-templates/actions/components/create-configmap-dotnet@main
      # - name: "Replace Variable Group '${{ matrix.AMBIENTE }}'"
      #   uses: Illusion-Factory-Labs/github-repo-templates/actions/components/replace-tokens@main
      #   with:
      #     FILES: "./**/k8s/*.yaml"
      #     TOKEN_PREFIX: "#{"
      #     TOKEN_SUFFIX: "}#"
      # - name: "Verificar PathBase esperado pelo deploy no AKS"
      #   uses: Illusion-Factory-Labs/github-repo-templates/actions/quality/code-check-dotnet@main