name: Playground Workflow

on:
  workflow_dispatch:
    inputs:
      AMBIENTES:
        required: false
        type: choice
        options:
          - '["des"]'
          - '["qa"]'
          - '["tqs"]'
          - '["prd"]'
          - '["des","qa"]'
          - '["des","tqs"]'
          - '["des","prd"]'
          - '["des","qa","tqs"]'
          - '["des","qa","tqs","prd"]'
        default: '["des","qa","tqs","prd"]'

permissions:
  contents: read

env:
  BUILD_VERSION: "1.0.0"
  DOTNET_VERSION: "8.0"
  ADV_SEC_LANG: "csharp"
  GLOBAL_REPO_VAR: github-repo-variables
  GH_PAT: ${{ secrets.GH_PAT }}
  WF_APP_ID: ${{ secrets.WF_APP_ID }}
  WF_APP_PRIVATE_KEY: ${{ secrets.WF_APP_PRIVATE_KEY }}
  GITHUB_REPOSITORY_OWNER: ${{ github.repository_owner }}

defaults:
  run:
    shell: bash

jobs:
  test-variables:
    runs-on: ubuntu-latest
    outputs:
      json: ${{ steps.temp-env-exists.outputs.json }}
    strategy:
      fail-fast: false
      matrix:
        AMBIENTE: ${{ fromJSON(inputs.AMBIENTES) }}
    environment: ${{ matrix.AMBIENTE == 'prd' && 'prd-temp' || (matrix.AMBIENTE == 'tqs' &&  'tqs-temp' || matrix.AMBIENTE) }}
    steps:
      - name: "Api Dotnet Variables"
        uses: Illusion-Factory-Labs/github-repo-templates/actions/context/dotnet-api@main
        with:
          AMBIENTE: ${{ matrix.AMBIENTE }}
      - name: "Token Create"
        uses: Illusion-Factory-Labs/github-repo-templates/actions/auth/githubapp@main
      - name: "Sincronizar ambiente temporário para importação de variáveis (evitar aprovação manual)"
        id: sync-temp-env-vars
        if: ${{ matrix.AMBIENTE == 'prd' || matrix.AMBIENTE == 'tqs' }}
        uses: Illusion-Factory-Labs/github-repo-templates/actions/components/sync-github-env-vars@main
      - name: "File Variable Groups '${{ matrix.AMBIENTE }}'"
        id: file-variable-group
        uses: Illusion-Factory-Labs/github-repo-templates/actions/components/file-variable-group@main
      - name: "Load Variable Groups '${{ matrix.AMBIENTE }}'"
        uses: Illusion-Factory-Labs/github-repo-templates/actions/components/load-variable-group@main
        with:
          VARS_FILE: ${{ steps.file-variable-group.outputs.VARS_FILE }}
          VARS_CONTEXT: ${{ toJson(vars) }}
          VARS_TEMP_ENV: ${{ steps.sync-temp-env-vars.outputs.changed_variables_json }}

      - name: "Checar necessidade remoção de ambiente temporário"
        id: temp-env-exists
        run: |
          if [[ "${{ matrix.AMBIENTE  }}" == 'prd' || "${{ matrix.AMBIENTE }}" == 'tqs' ]]; then
            echo "need_to_remove=true" >> "$GITHUB_OUTPUT"
          else
            echo "need_to_remove=false" >> "$GITHUB_OUTPUT"
          fi
      
  remove-temp-env:
    runs-on: ubuntu-latest
    needs: test-variables
    if: needs.test-variables.outputs.need_to_remove == 'true'
    steps:
      - name: "Token Create"
        uses: Illusion-Factory-Labs/github-repo-templates/actions/auth/githubapp@main
        
      - name: "Remover ambiente temporário de importação de variáveis"
        uses: Illusion-Factory-Labs/github-repo-templates/actions/components/remove-github-env@main
        